sudo: false
language: node_js
notifications:
  email: false
node_js:
  - node
  - '5'
  - '4'
  - iojs-v3
  - iojs-v2
  - iojs-v1
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
script:
  - npm run test:cov
after_script:
  - npm run coveralls
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
